<?php
return
[
'Authorization' => [
	'SUPER_ADMIN' => 1,
	'ORG_ADMIN' => 2,
	'USER' => 3,
	'ADMIN' => 4,
	'data' => [
		['value' => 1, 'text' => 'Super Admin'],
		['value' => 2, 'text' => 'Organization Admin'],
		['value' => 3, 'text' => 'User'],
		['value' => 4, 'text' => 'Admin'],
	]
],

'MediaType' => [
	'DP' => 1,
	'COVER_PHOTO' => 2,
	'ATTACHMENT' => 3,
	'PERMISSION_LETTER' => 4,
	'NIC' => 5,
	'PASSPORT' => 6,
	'CV' => 7,
	'COVER_LETTER' => 8,
	'REGISTRATION_LETTER' => 9,
	'MEMORANDUM_ARTICLE' => 10,
	'AUTHORITY_LETTER' => 11,
	'ORG_PROFILE' => 12,
	'AGREEMENT_LETTER' => 13,
	'LEASE_AGREEMENT' => 14,
	'SECP_CERTIFICATE' => 15,
	'REALIZATION_CERTIFICATE' => 16,
	'ANNUAL_REPORT' => 17,
	'RECEIPT' => 18,
	'TAX_RETURN' => 19,
	'FINANCIAL_STATEMENT' => 20,
	'AUDIT_REPORT' => 21,
	'data' => [
		['value' => 1, 'text' => 'Profile Picture'],
		['value' => 2, 'text' => 'Cover Photo'],
		['value' => 3, 'text' => 'Attachment'],
		['value' => 4, 'text' => 'Permission Letter'],
		['value' => 5, 'text' => 'NIC'],
		['value' => 6, 'text' => 'Passport'],
		['value' => 7, 'text' => 'CV'],
		['value' => 8, 'text' => 'Cover Letter'],
		['value' => 9, 'text' => ''],
		['value' => 10, 'text' => ''],
		['value' => 11, 'text' => ''],
		['value' => 12, 'text' => ''],
		['value' => 13, 'text' => ''],
		['value' => 14, 'text' => ''],
		['value' => 15, 'text' => ''],
		['value' => 16, 'text' => ''],
		['value' => 17, 'text' => ''],
		['value' => 18, 'text' => ''],
		['value' => 19, 'text' => ''],
		['value' => 20, 'text' => ''],
		['value' => 21, 'text' => ''],
	]
],

'NotificationType' => [
	'EMAIL' => 1,
	'SMS' => 2,
	'IM' => 3,
	'SYSTEM' => 4,
	'data' => [
		['value' => 1, 'text' => 'Email'],
		['value' => 2, 'text' => 'SMS'],
		['value' => 3, 'text' => 'Instant Message'],
		['value' => 4, 'text' => 'System'],
	]
],

'ContactType' => [
	'USER' => 1,
	'ORGANIZATION' => 2,
	'PRINCIPAL_OFFICER' => 3,
	'DIRECTOR' => 4,
	'LOCAL_CONTACT' => 5,
	'LOCAL_SPONSOR' => 6,
	'AGENT' => 7,
	'PARTNER_COMPANY' => 8,
	'PARTNER_PERSON' => 9,
	'data' => [
		['value' => 1, 'text' => 'User'],
		['value' => 2, 'text' => 'Organization'],
		['value' => 3, 'text' => 'Principal Officer'],
		['value' => 4, 'text' => 'Director'],
		['value' => 5, 'text' => 'Local Contact'],
		['value' => 6, 'text' => 'Local Sponsor'],
		['value' => 7, 'text' => 'Agent'],
		['value' => 8, 'text' => 'Partner Company'],
		['value' => 9, 'text' => 'Partner Person'],
	]
],

'ApplicationStatus' => [
	'NEW' => 1,
	'INITIATED' => 2,
	'SUBMITTED' => 3,
	'FORWARDED' => 4,
	'CIRCULATED' => 5,
	'APPROVED' => 6,
	'REJECTED' => 7,
	'COMMENTED' => 8,
	'UPDATED' => 9,
	'REVERTED' => 10,
	'HELD' => 11,
	'APPROVABLE' => 12,
	'REJECTABLE' => 13,
	'PAYMENT_PENDING' => 14,
	'PENDING' => 15,
	'SHARED' => 16,
	'ACTIVE' => 17,
	'INACTIVE' => 18,
	'RENEWED' => 19,
	'data' => [
		['value' => 1, 'text' => 'New'],
		['value' => 2, 'text' => 'Initiated'],
		['value' => 3, 'text' => 'Submitted'],
		['value' => 4, 'text' => 'Forwarded'],
		['value' => 5, 'text' => 'Circulated'],
		['value' => 6, 'text' => 'Approved'],
		['value' => 7, 'text' => 'Rejected'],
		['value' => 8, 'text' => 'Commented'],
		['value' => 9, 'text' => 'Updated'],
		['value' => 10, 'text' => 'Reverted'],
		['value' => 11, 'text' => 'Held'],
		['value' => 12, 'text' => 'Approvable'],
		['value' => 13, 'text' => 'Rejectable'],
		['value' => 14, 'text' => 'Payment Pending'],
		['value' => 15, 'text' => 'Pending'],
		['value' => 16, 'text' => 'Shared'],
		['value' => 17, 'text' => 'Active'],
		['value' => 18, 'text' => 'In Active'],
		['value' => 19, 'text' => 'Renewed'],
	]
],

'ServiceType' => [
	'BRANCH' => 1,
	'SUB_BRANCH' => 2,
	'BRANCH_CONVERSION' => 3,
	'LIAISON' => 4,
	'SUB_LIAISON' => 5,
	'LIAISON_CONVERSION' => 6,
	'data' => [
		['value' => 1, 'text' => 'Branch Office'],
		['value' => 2, 'text' => 'Sub-Branch Office'],
		['value' => 3, 'text' => 'Branch Conversion'],
		['value' => 4, 'text' => 'Liaison Office'],
		['value' => 5, 'text' => 'Sub-Liaison Office'],
		['value' => 6, 'text' => 'Liaison Conversion'],
	]
],

'Sector' => [
	'FOOD' => 1,
	'FOOD_PACKAGING' => 2,
	'BEVERAGES' => 3,
	'TOBACCO_CIGARETTES' => 4,
	'SUGAR' => 5,
	'TEXTILES' => 6,
	'PAPER_PULP' => 7,
	'LEATHER_LEATHER_PRODUCTS' => 8,
	'RUBBER_RUBBER_PRODUCTS' => 9,
	'CHEMICALS' => 10,
	'PETRO_CHEMICALS' => 11,
	'PETROLEUM_REFINING' => 12,
	'MINING_QUARRYING' => 13,
	'OIL_GAS_EXPLORATIONS' => 14,
	'PHARMACEUTICALS_O_T_C_PRODUCTS' => 15,
	'COSMETICS' => 16,
	'FERTILIZERS' => 17,
	'CEMENT' => 18,
	'CERAMICS' => 19,
	'BASIC_METALS' => 20,
	'METAL_PRODUCTS' => 21,
	'MACHINERYOTHERTHAN_ELECTRICAL' => 22,
	'ELECTRICAL_MACHINERY' => 23,
	'ELECTRONICS' => 24,
	'POWER' => 25,
	'CONSTRUCTION' => 26,
	'TRADE' => 27,
	'TRANSPORT' => 28,
	'TRANSPORT_EQUIPMENT_AUTOMOBILES' => 29,
	'TOURISM' => 30,
	'STORAGE_FACILITIES' => 31,
	'TELECOMMUNICATIONS' => 32,
	'INFORMATION_TECHNOLOGY' => 33,
	'FINANCIAL_BUSINESS' => 34,
	'SOCIAL_SERVICES' => 35,
	'PERSONAL_SERVICES' => 36,
	'OTHER' => 37,
	'data' => [
		['value' => 1, 'text' => 'Food'],
		['value' => 2, 'text' => 'Food Packaging'],
		['value' => 3, 'text' => 'Beverages'],
		['value' => 4, 'text' => 'Tobacco & Cigarettes'],
		['value' => 5, 'text' => 'Sugar'],
		['value' => 6, 'text' => 'Textiles'],
		['value' => 7, 'text' => 'Paper & Pulp'],
		['value' => 8, 'text' => 'Leather & Leather Products'],
		['value' => 9, 'text' => 'Rubber & Rubber Products'],
		['value' => 10, 'text' => 'Chemicals'],
		['value' => 11, 'text' => 'Petro Chemicals'],
		['value' => 12, 'text' => 'Petroleum Refining'],
		['value' => 13, 'text' => 'Mining & Quarrying'],
		['value' => 14, 'text' => 'Oil & Gas Explorations'],
		['value' => 15, 'text' => 'Pharmaceuticals & OTC Products'],
		['value' => 16, 'text' => 'Cosmetics'],
		['value' => 17, 'text' => 'Fertilizers'],
		['value' => 18, 'text' => 'Cement'],
		['value' => 19, 'text' => 'Ceramics'],
		['value' => 20, 'text' => 'Basic Metals'],
		['value' => 21, 'text' => 'Metal Products'],
		['value' => 22, 'text' => 'Machinery other than Electrical'],
		['value' => 23, 'text' => 'Electrical Machinery'],
		['value' => 24, 'text' => 'Electronics'],
		['value' => 25, 'text' => 'Power'],
		['value' => 26, 'text' => 'Construction'],
		['value' => 27, 'text' => 'Trade'],
		['value' => 28, 'text' => 'Transport'],
		['value' => 29, 'text' => 'Transport Equipment(Automobiles)'],
		['value' => 30, 'text' => 'Tourism'],
		['value' => 31, 'text' => 'Storage Facilities'],
		['value' => 32, 'text' => 'Telecommunications'],
		['value' => 33, 'text' => 'Information Technology'],
		['value' => 34, 'text' => 'Financial Business'],
		['value' => 35, 'text' => 'Social Services'],
		['value' => 36, 'text' => 'Personal Services'],
		['value' => 37, 'text' => 'Other'],
	]
],

'AgentType' => [
	'LAW' => 1,
	'ACCOUNTANT' => 2,
	'TAX_CONSULTANT' => 3,
	'OTHER' => 4,
	'data' => [
		['value' => 1, 'text' => 'Law Firm'],
		['value' => 2, 'text' => 'Chartered Accountancy Firm'],
		['value' => 3, 'text' => 'Tax Consultancy Firm'],
		['value' => 4, 'text' => 'Other'],
	]
],

'ProfileStatus' => [
	'ACTIVE' => 1,
	'BLOCKED' => 2,
	'data' => [
		['value' => 1, 'text' => 'Active'],
		['value' => 2, 'text' => 'Blocked'],
	]
],
];