<?php

namespace App\Lookups;

class Country extends BaseLookup{

	const DATA = [
		['value'=>'XKS','text'=>'Kosovo'],
		['value'=>'XSV','text'=>'Svalbard'],
		['value'=>'XWB','text'=>'West Bank'],
		['value'=>'YEM','text'=>'Yemen'],
		['value'=>'MYT','text'=>'Mayotte'],
		['value'=>'ZAF','text'=>'South Africa'],
		['value'=>'ZMB','text'=>'Zambia'],
		['value'=>'ZWE','text'=>'Zimbabwe'],
		['value'=>'KAZ','text'=>'Kazakhstan'],
		['value'=>'LAO','text'=>'Laos'],
		['value'=>'LBN','text'=>'Lebanon'],
		['value'=>'LCA','text'=>'Saint Lucia'],
		['value'=>'LIE','text'=>'Liechtenstein'],
		['value'=>'LKA','text'=>'Sri Lanka'],
		['value'=>'LBR','text'=>'Liberia'],
		['value'=>'LSO','text'=>'Lesotho'],
		['value'=>'LTU','text'=>'Lithuania'],
		['value'=>'LUX','text'=>'Luxembourg'],
		['value'=>'LVA','text'=>'Latvia'],
		['value'=>'LBY','text'=>'Libya'],
		['value'=>'MAR','text'=>'Morocco'],
		['value'=>'MCO','text'=>'Monaco'],
		['value'=>'MDA','text'=>'Moldova'],
		['value'=>'MNE','text'=>'Montenegro'],
		['value'=>'MAF','text'=>'Saint Martin'],
		['value'=>'MDG','text'=>'Madagascar'],
		['value'=>'MHL','text'=>'Marshall Islands'],
		['value'=>'MKD','text'=>'Macedonia'],
		['value'=>'MLI','text'=>'Mali'],
		['value'=>'MMR','text'=>'Burma'],
		['value'=>'MNG','text'=>'Mongolia'],
		['value'=>'MAC','text'=>'Macau, China'],
		['value'=>'MTQ','text'=>'Martinique'],
		['value'=>'MRT','text'=>'Mauritania'],
		['value'=>'MSR','text'=>'Montserrat'],
		['value'=>'MLT','text'=>'Malta'],
		['value'=>'MUS','text'=>'Mauritius'],
		['value'=>'MDV','text'=>'Maldives'],
		['value'=>'MWI','text'=>'Malawi'],
		['value'=>'MEX','text'=>'Mexico'],
		['value'=>'MYS','text'=>'Malaysia'],
		['value'=>'MOZ','text'=>'Mozambique'],
		['value'=>'NAM','text'=>'Namibia'],
		['value'=>'NCL','text'=>'New Caledonia'],
		['value'=>'NER','text'=>'Niger'],
		['value'=>'NFK','text'=>'Norfolk Island'],
		['value'=>'NGA','text'=>'Nigeria'],
		['value'=>'NIC','text'=>'Nicaragua'],
		['value'=>'NLD','text'=>'Netherlands'],
		['value'=>'NOR','text'=>'Norway'],
		['value'=>'NPL','text'=>'Nepal'],
		['value'=>'NIU','text'=>'Niue'],
		['value'=>'NZL','text'=>'New Zealand'],
		['value'=>'OMN','text'=>'Oman'],
		['value'=>'PAN','text'=>'Panama'],
		['value'=>'PER','text'=>'Peru'],
		['value'=>'PYF','text'=>'French Polynesia'],
		['value'=>'PNG','text'=>'Papua New Guinea'],
		['value'=>'PHL','text'=>'Philippines'],
		['value'=>'PAK','text'=>'Pakistan'],
		['value'=>'POL','text'=>'Poland'],
		['value'=>'SPM','text'=>'Saint Pierre And Miquelon'],
		['value'=>'PCN','text'=>'Pitcairn Islands'],
		['value'=>'PRT','text'=>'Portugal'],
		['value'=>'PLW','text'=>'Palau'],
		['value'=>'PRY','text'=>'Paraguay'],
		['value'=>'QAT','text'=>'Qatar'],
		['value'=>'REU','text'=>'Reunion'],
		['value'=>'ROU','text'=>'Romania'],
		['value'=>'SRB','text'=>'Serbia'],
		['value'=>'RUS','text'=>'Russia'],
		['value'=>'RWA','text'=>'Rwanda'],
		['value'=>'SAU','text'=>'Saudi Arabia'],
		['value'=>'SLB','text'=>'Solomon Islands'],
		['value'=>'SYC','text'=>'Seychelles'],
		['value'=>'SDN','text'=>'Sudan'],
		['value'=>'SWE','text'=>'Sweden'],
		['value'=>'SGP','text'=>'Singapore'],
		['value'=>'SHN','text'=>'Saint Helena, Ascension, And Tristan Da Cunha'],
		['value'=>'SVN','text'=>'Slovenia'],
		['value'=>'SVK','text'=>'Slovakia'],
		['value'=>'SLE','text'=>'Sierra Leone'],
		['value'=>'SMR','text'=>'San Marino'],
		['value'=>'SEN','text'=>'Senegal'],
		['value'=>'SOM','text'=>'Somalia'],
		['value'=>'SUR','text'=>'Suriname'],
		['value'=>'SSD','text'=>'South Sudan'],
		['value'=>'STP','text'=>'Sao Tome And Principe'],
		['value'=>'SLV','text'=>'El Salvador'],
		['value'=>'SXM','text'=>'Sint Maarten'],
		['value'=>'SYR','text'=>'Syria'],
		['value'=>'SWZ','text'=>'Swaziland'],
		['value'=>'TCA','text'=>'Turks And Caicos Islands'],
		['value'=>'TCD','text'=>'Chad'],
		['value'=>'TGO','text'=>'Togo'],
		['value'=>'THA','text'=>'Thailand'],
		['value'=>'TJK','text'=>'Tajikistan'],
		['value'=>'TLS','text'=>'Timor-Leste'],
		['value'=>'TKM','text'=>'Turkmenistan'],
		['value'=>'TUN','text'=>'Tunisia'],
		['value'=>'TON','text'=>'Tonga'],
		['value'=>'TUR','text'=>'Turkey'],
		['value'=>'TTO','text'=>'Trinidad And Tobago'],
		['value'=>'TUV','text'=>'Tuvalu'],
		['value'=>'TWN','text'=>'Taiwan, China'],
		['value'=>'TZA','text'=>'Tanzania'],
		['value'=>'UKR','text'=>'Ukraine'],
		['value'=>'UGA','text'=>'Uganda'],
		['value'=>'URY','text'=>'Uruguay'],
		['value'=>'UZB','text'=>'Uzbekistan'],
		['value'=>'VCT','text'=>'Saint Vincent And The Grenadines'],
		['value'=>'VEN','text'=>'Venezuela'],
		['value'=>'VGB','text'=>'Virgin Islands, British'],
		['value'=>'VNM','text'=>'Vietnam'],
		['value'=>'VUT','text'=>'Vanuatu'],
		['value'=>'WLF','text'=>'Wallis And Futuna'],
		['value'=>'WSM','text'=>'Samoa'],
		['value'=>'AND','text'=>'Andorra'],
		['value'=>'ARE','text'=>'United Arab Emirates'],
		['value'=>'AFG','text'=>'Afghanistan'],
		['value'=>'ATG','text'=>'Antigua And Barbuda'],
		['value'=>'AIA','text'=>'Anguilla'],
		['value'=>'ALB','text'=>'Albania'],
		['value'=>'ARM','text'=>'Armenia'],
		['value'=>'AGO','text'=>'Angola'],
		['value'=>'ARG','text'=>'Argentina'],
		['value'=>'AUT','text'=>'Austria'],
		['value'=>'AUS','text'=>'Australia'],
		['value'=>'ABW','text'=>'Aruba'],
		['value'=>'AZE','text'=>'Azerbaijan'],
		['value'=>'BIH','text'=>'Bosnia And Herzegovina'],
		['value'=>'BRB','text'=>'Barbados'],
		['value'=>'BGD','text'=>'Bangladesh'],
		['value'=>'BEL','text'=>'Belgium'],
		['value'=>'BFA','text'=>'Burkina Faso'],
		['value'=>'BGR','text'=>'Bulgaria'],
		['value'=>'BHR','text'=>'Bahrain'],
		['value'=>'BDI','text'=>'Burundi'],
		['value'=>'BEN','text'=>'Benin'],
		['value'=>'BLM','text'=>'Saint Barthelemy'],
		['value'=>'BMU','text'=>'Bermuda'],
		['value'=>'BRN','text'=>'Brunei'],
		['value'=>'BOL','text'=>'Bolivia'],
		['value'=>'BRA','text'=>'Brazil'],
		['value'=>'BHS','text'=>'Bahamas, The'],
		['value'=>'BTN','text'=>'Bhutan'],
		['value'=>'BWA','text'=>'Botswana'],
		['value'=>'BLR','text'=>'Belarus'],
		['value'=>'BLZ','text'=>'Belize'],
		['value'=>'CAN','text'=>'Canada'],
		['value'=>'COD','text'=>'Congo (Kinshasa)'],
		['value'=>'CAF','text'=>'Central African Republic'],
		['value'=>'COG','text'=>'Congo (Brazzaville)'],
		['value'=>'CHE','text'=>'Switzerland'],
		['value'=>'CIV','text'=>'Côte D’Ivoire'],
		['value'=>'COK','text'=>'Cook Islands'],
		['value'=>'CHL','text'=>'Chile'],
		['value'=>'CMR','text'=>'Cameroon'],
		['value'=>'CHN','text'=>'China'],
		['value'=>'COL','text'=>'Colombia'],
		['value'=>'CRI','text'=>'Costa Rica'],
		['value'=>'CUB','text'=>'Cuba'],
		['value'=>'CPV','text'=>'Cabo Verde'],
		['value'=>'CUW','text'=>'Curaçao'],
		['value'=>'CXR','text'=>'Christmas Island'],
		['value'=>'CYP','text'=>'Cyprus'],
		['value'=>'CZE','text'=>'Czechia'],
		['value'=>'DEU','text'=>'Germany'],
		['value'=>'DJI','text'=>'Djibouti'],
		['value'=>'DNK','text'=>'Denmark'],
		['value'=>'DMA','text'=>'Dominica'],
		['value'=>'DOM','text'=>'Dominican Republic'],
		['value'=>'DZA','text'=>'Algeria'],
		['value'=>'ECU','text'=>'Ecuador'],
		['value'=>'EST','text'=>'Estonia'],
		['value'=>'EGY','text'=>'Egypt'],
		['value'=>'ERI','text'=>'Eritrea'],
		['value'=>'ESP','text'=>'Spain'],
		['value'=>'ETH','text'=>'Ethiopia'],
		['value'=>'FIN','text'=>'Finland'],
		['value'=>'FJI','text'=>'Fiji'],
		['value'=>'FLK','text'=>'Falkland Islands (Islas Malvinas)'],
		['value'=>'FSM','text'=>'Micronesia, Federated States Of'],
		['value'=>'FRO','text'=>'Faroe Islands'],
		['value'=>'FRA','text'=>'France'],
		['value'=>'GAB','text'=>'Gabon'],
		['value'=>'GBR','text'=>'United Kingdom'],
		['value'=>'GRD','text'=>'Grenada'],
		['value'=>'GEO','text'=>'Georgia'],
		['value'=>'GUF','text'=>'French Guiana'],
		['value'=>'GGY','text'=>'Guernsey'],
		['value'=>'GHA','text'=>'Ghana'],
		['value'=>'GIB','text'=>'Gibraltar'],
		['value'=>'GRL','text'=>'Greenland'],
		['value'=>'GMB','text'=>'Gambia, The'],
		['value'=>'GIN','text'=>'Guinea'],
		['value'=>'GLP','text'=>'Guadeloupe'],
		['value'=>'GNQ','text'=>'Equatorial Guinea'],
		['value'=>'GRC','text'=>'Greece'],
		['value'=>'SGS','text'=>'South Georgia And South Sandwich Islands'],
		['value'=>'GTM','text'=>'Guatemala'],
		['value'=>'GNB','text'=>'Guinea-Bissau'],
		['value'=>'GUY','text'=>'Guyana'],
		['value'=>'HKG','text'=>'Hong Kong, China'],
		['value'=>'HND','text'=>'Honduras'],
		['value'=>'HRV','text'=>'Croatia'],
		['value'=>'HTI','text'=>'Haiti'],
		['value'=>'HUN','text'=>'Hungary'],
		['value'=>'IDN','text'=>'Indonesia'],
		['value'=>'IRL','text'=>'Ireland'],
		['value'=>'ISR','text'=>'Israel'],
		['value'=>'IMN','text'=>'Isle Of Man'],
		['value'=>'IND','text'=>'India'],
		['value'=>'IRQ','text'=>'Iraq'],
		['value'=>'IRN','text'=>'Iran'],
		['value'=>'ISL','text'=>'Iceland'],
		['value'=>'ITA','text'=>'Italy'],
		['value'=>'JEY','text'=>'Jersey'],
		['value'=>'JAM','text'=>'Jamaica'],
		['value'=>'JOR','text'=>'Jordan'],
		['value'=>'JPN','text'=>'Japan'],
		['value'=>'KEN','text'=>'Kenya'],
		['value'=>'KGZ','text'=>'Kyrgyzstan'],
		['value'=>'KHM','text'=>'Cambodia'],
		['value'=>'KIR','text'=>'Kiribati'],
		['value'=>'COM','text'=>'Comoros'],
		['value'=>'KNA','text'=>'Saint Kitts And Nevis'],
		['value'=>'PRK','text'=>'Korea, North'],
		['value'=>'KOR','text'=>'Korea, South'],
		['value'=>'KWT','text'=>'Kuwait'],
		['value'=>'CYM','text'=>'Cayman Islands'],
		['value'=>'ASM','text'=>'American Samoa'],
		['value'=>'GUM','text'=>'Guam'],
		['value'=>'MNP','text'=>'Northern Mariana Islands'],
		['value'=>'USA','text'=>'United States'],
	];
}